version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: start_app
      timeout: 30
      runas: root
  ApplicationStop:
    - location: stop_app
      timeout: 30
      runas: root
