        version: 1.0
        os: linux
        files:
        - source: /index.html
            destination: /var/www/html/
        hooks:
        BeforeInstall:
            - location: stop_app
            timeout: 300
            runas: root
        AfterInstall:
            - location: start_app
            timeout: 300
            runas: root
